# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:

    runs-on: macos-11
    env:
      VUE_APP_API_URL: http://146.56.134.252:8080
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: build dist
        run: yarn build
      - run: yarn make --arch x64
      - run: yarn make --arch arm64
      - name: Archive production artifacts - darwin x64
        uses: actions/upload-artifact@v2
        with:
          name: account-0.1.0-darwin-x64.dmg
          path: out/make/account-0.1.0-x64.dmg
      - name: Archive production artifacts - darwin arm64
        uses: actions/upload-artifact@v2
        with:
          name: account-0.1.0-darwin-arm64.dmg
          path: out/make/account-0.1.0-arm64.dmg
  build-windows:
    runs-on: windows-latest
    env:
      VUE_APP_API_URL: http://146.56.134.252:8080
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: build dist
        run: yarn build
      - name: Build The Executable File
        run: yarn make
      - name: Archive production artifacts - set up
        uses: actions/upload-artifact@v2
        with:
          name: account-0.1.0-windows-x64.exe
          path: out/make/squirrel.windows/x64/account-0.1.0 Setup.exe
      - name: Archive production artifacts - nupkg
        uses: actions/upload-artifact@v2
        with:
          name: account-0.1.0-windows-x64.nupkg
          path: out/make/squirrel.windows/x64/account-0.1.0-full.nupkg
      - name: Archive production artifacts - release
        uses: actions/upload-artifact@v2
        with:
          name: account-0.1.0-windows-RELEASES
          path: out/make/squirrel.windows/x64/RELEASES
